config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/dashboard', to: 'users#show'
  resources :users, only: [:new, :index, :create,:edit,:update]
  resources :items, only: [:index]
  get '/items/:slug', to: 'items#show', as: "item"
  resources :categories, only: [:index]
  get '/categories/:slug', to: 'categories#show', as: "category"
  resources :cart_items, only: [:create, :show, :update, :destroy]
  get '/cart', to: 'cart_items#index'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:create,:show]
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :new, :create]
    get '/items/:slug/edit', to: 'items#edit', as: 'edit_item'
    patch '/items/:slug', to: 'items#update', as: 'item'
    resources :orders, only: [:index, :show]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @admin = current_user
    @orders = Order.all
    @categories = Category.all
  end
end

app/views/admin/dashboard/index.html.erb
<div>
  <h2 class="center">Administrator Dashboard</h2>
  <hr>
  <br>
  <div class="row">
    <div class="col s3">
      <%= link_to 'View items', admin_items_path, class: "waves-effect waves-light btn #3e2723 brown darken-4" %>
    </div>

    <div class="col s3">
      <%= link_to "Edit Account", edit_user_path(@admin), class: "waves-effect waves-light btn #3e2723 brown darken-4" %>
    </div>

    <div class="col s3">
      <a class='dropdown-button btn #3e2723 brown darken-4' href='<%= new_admin_item_path %>' data-activates='dropdown1'>Add New Item</a>
      <ul id='dropdown1' class='dropdown-content'>
        <li><p class="center">categories</p></li>
        <li class="divider"></li>
        <% @categories.each do |category| %>
          <li id="item-create-<%= category.id %>"><%= link_to "#{category.name}", new_admin_item_path(category_id: category.id) %></li>
        <% end %>
      </ul>
    </div>

    <div class="col 3">
      <a class='dropdown-button btn #3e2723 brown darken-4' href='<%= new_admin_item_path %>' data-activates='dropdown2'>Order Status</a>
      <ul id='dropdown2' class='dropdown-content'>
        <li><p class="center">Status</p></li>
        <li class="divider"></li>
        <% @admin.orders.statuses.each do |status, num| %>
          <li><%= link_to "#{status}", "#", id: "status-#{status}" %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <ul class="collection with-header">
        <li class="collection-header"><strong>Order Status</strong></li>
        <li class="collection-item">Ordered: <%= Order.where(status: 0).count(:status) %></li>
        <li class="collection-item">Paid: <%= Order.where(status: 1).count(:status) %></li>
        <li class="collection-item">Cancelled: <%= Order.where(status: 2).count(:status) %></li>
        <li class="collection-item">Completed: <%= Order.where(status: 3).count(:status) %></li>
      </ul>
    </div>
  </div>

  <div class="order-info">
    <% @orders.each do |order| %>
      <ul class="collapsible popout order" data-collapsible="accordion" data-status="<%= order.status %>">
        <li>
          <div class="collapsible-header collapsible-header<%= order.id %>">
            <%= link_to "Order number: #{order.id}", admin_order_path(order) %>
          </div>
          <div class="collapsible-body">
            <p>Order Quantity: <%= order.quantity %></p><br>
            <p>Order Total: <%= number_to_currency(order.sum) %></p>
          </div>
        </li>
      </ul>
    <%end %>
  </div>
</div>