config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/dashboard', to: 'users#show'
  resources :users, only: [:new, :index, :create,:edit,:update]
  resources :items, only: [:index]
  get '/items/:slug', to: 'items#show', as: "item"
  resources :categories, only: [:index]
  get '/categories/:slug', to: 'categories#show', as: "category"
  resources :cart_items, only: [:create, :show, :update, :destroy]
  get '/cart', to: 'cart_items#index'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:create,:show]
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :new, :create]
    get '/items/:slug/edit', to: 'items#edit', as: 'edit_item'
    patch '/items/:slug', to: 'items#update', as: 'item'
    resources :orders, only: [:index, :show]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :title, :description, :price , :image, presence: true
  validates :title, uniqueness: true
  has_many :order_items
  has_many :orders, through: :order_items
  before_save :set_slug

  def to_param
    slug
  end

  def set_slug
    self.slug = title.parameterize
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

  def new
    @item = Category.find(params[:category_id]).items.new
  end

  def create
    @item = Category.find(params[:item][:category_id]).items.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      flash[:errors] = "Missing fields. Please try again."
      redirect_to new_admin_item_path
    end
  end

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find_by(slug: params[:slug])
  end

  def update
    @item = Item.find_by(slug: params[:slug])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find_by(slug: params[:slug])
  end
end

app/views/items/index.html.erb
<br>
<h1 class='container'>Menu Items</h1>
<br>

<div class="row">
  <div class="col s9">
    <ul class="collection">
      <%@items.each do |item| %>
      <li class="collection-item avatar" id="item<%= item.id %>">
        <%= image_tag(item.image, class: "circle") %>
        <strong><span class="title<%= item.title %>"><%=link_to item.title, item_path(item.slug) %></span></strong>
        <p><%= number_to_currency(item.price) %></p>
        <span class="secondary-content"><%= button_to "Add to Cart", cart_items_path(id: item.id), id: "add-#{item.id}" %></span>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col s3" id="butooon">
    <%= button_to cart_path, method: :get, class: "waves-effect waves-light btn black" do %>
      <i class="fa fa-shopping-cart"> View Cart</i>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col s8 m7">
    <div class="card hoverable">
      <div class="card-image">
        <%= image_tag(@item.image) %>
        <span class="card-title"><%= @item.title.capitalize %></span>
      </div>
      <div class="card-content">
        <p><%= number_to_currency(@item.price) %></p>
      </div>
      <div class="card-action">
        <%= link_to "Back to Menu", items_path %>
      </div>
    </div>
  </div>
  <div class="col 4">
    <p><%= @item.description %></p>
  </div>
</div>