config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/dashboard', to: 'users#show'
  resources :users, only: [:new, :index, :create,:edit,:update]
  resources :items, only: [:index]
  get '/items/:slug', to: 'items#show', as: "item"
  resources :categories, only: [:index]
  get '/categories/:slug', to: 'categories#show', as: "category"
  resources :cart_items, only: [:create, :show, :update, :destroy]
  get '/cart', to: 'cart_items#index'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:create,:show]
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :new, :create]
    get '/items/:slug/edit', to: 'items#edit', as: 'edit_item'
    patch '/items/:slug', to: 'items#update', as: 'item'
    resources :orders, only: [:index, :show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates :name, presence: true
  before_save :set_slug

  def to_param
    slug
  end

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(slug: params[:slug])
  end
end

app/views/categories/index.html.erb
<br>
<h1 class="container">Categories</h1>

<ul class="collection">
  <%@categories.each do |category| %>
    <li class="collection-item" id="category<%= category.id %>"><%=link_to category.name, category_path(category.slug) %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<div class="row">
  <div class="col s8">
    <table>
      <thead>
        <tr>
          <th data-field="name">Item Name</th>
          <th data-field="price"> Price</th>
        </tr>
        <h1 class="container">Category: <%="#{@category.name}" %></h1>
        <% @category.items.each do |item| %>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to item.title, item_path(item) %></td>
          <td> <%=number_to_currency(item.price) %></td>
          <% end %>
      </tbody>
    </table>
    <br>
    <div class="col s6">
      <%= link_to "Back to Categories", categories_path, class: 'waves-effect waves-light btn black' %>
    </div>
  </div>
</div>