config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/dashboard', to: 'users#show'
  resources :users, only: [:new, :index, :create,:edit,:update]
  resources :items, only: [:index]
  get '/items/:slug', to: 'items#show', as: "item"
  resources :categories, only: [:index]
  get '/categories/:slug', to: 'categories#show', as: "category"
  resources :cart_items, only: [:create, :show, :update, :destroy]
  get '/cart', to: 'cart_items#index'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:create,:show]
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :items, only: [:index, :new, :create]
    get '/items/:slug/edit', to: 'items#edit', as: 'edit_item'
    patch '/items/:slug', to: 'items#update', as: 'item'
    resources :orders, only: [:index, :show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCoffeeOrder</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper #000000 black">
          <%= link_to root_path, class: "brand-logo" do %>
            <i class="fa fa-coffee"> My Coffee Now</i>
          <% end %>
          <ul id="nav-mobile" class="right hide-on-med-and-down #3e2723 brown darken-4">
            <% if current_admin? %>
              <li><%= link_to "Dashboard", admin_dashboard_index_path %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% elsif current_user %>
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", login_path %></li>
              <li> <%= link_to "Sign Up", new_user_path %> </li>
            <% end %>
            <li><%= link_to "Menu", items_path %></li>
            <li><%= link_to "Cart", cart_path %></li>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <main>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%=content_tag :div, msg, class: "flash_#{type}" %>
      <% end %>
      <%= yield %>
    </div>
  </main>

</body>
</html>